version: '3'
services:
  db:
    image: mysql:latest
    container_name: docker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: clinicalsdb
    networks:
      - mynetwork

  web:
    build: .
    container_name: django-app
    environment:
      - DATABASE_NAME=clinicalsdb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=test1234
      - DATABASE_HOST=db
    depends_on:
      - db
    ports:
      - "10555:8000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
